# enum_discrim_align_threshold = 20
# fn_single_line = true
# format_macro_matchers = true
# match_block_trailing_comma = true
max_width = 120
# reorder_impl_items = true
# struct_field_align_threshold = 20
tab_spaces = 2
use_small_heuristics = "Max"
# version = "Two"
# where_single_line = true
